// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RehabDataProject.Data;

#nullable disable

namespace RehabDataProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230530213654_AddPatientInfoToDatabase")]
    partial class AddPatientInfoToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RehabDataProject.Models.Patient_Info", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("KneeROM")
                        .HasColumnType("float");

                    b.Property<int>("KneeStrength")
                        .HasColumnType("int");

                    b.Property<double>("LowerBackFlexionROM")
                        .HasColumnType("float");

                    b.Property<double>("LowerbackExtROM")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PainFreeWeightLifted")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Patients_Info");
                });
#pragma warning restore 612, 618
        }
    }
}
